config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :movies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age, :movie_id)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include Pagy::Backend
  require 'pagy/extras/bootstrap'

  before_action :set_movie, only: %i[show edit update destroy]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
    @pagy, @movies = pagy(@movies, items: 6) # Cambio @records por @movies  
  end

  # GET /movies/1 or /movies/1.json
  def show
    @movie = Movie.find(params[:id])
    @clients = Client.all
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
    @clients = Client.all
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend


end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id(client) %>" style="background-color: #f9f9f9; padding: 20px; border: 1px solid #ccc; border-radius: 5px;">
  <p style="font-size: 18px; color: #333; margin-bottom: 10px;">
    <strong>Nombre:</strong> <%= client.name %>
  </p>

  <p style="font-size: 16px; color: #555; margin-bottom: 5px;">
    <strong>Edad:</strong> <%= client.age %>
  </p>

  <div style="margin-bottom: 10px;">
    <%= image_tag client.movie.image, style: "max-width: 100%; height: auto; border: 1px solid #ccc; border-radius: 5px;" %>
  </div>

  <p style="font-size: 16px; color: #555; margin-bottom: 0;">
    <strong>Nombre:</strong> <%= client.movie.name %>
  </p>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :Edad, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :Pelicula, style: "display: block" %>
    <%= form.collection_select :movie_id, Movie.all, :id, :name, include_blank: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar cliente</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Ir al cliente", @client %> |
  <%= link_to "Volver a los clientes", clients_path, class:"btn btn-outline-secondary" %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<div id="clients" class="row">
  <% @clients.each_slice(3) do |client_slice| %>
    <div class="row">
      <% client_slice.each do |client| %>
        <div class="col-md-4">
          <%= render client %>
          <p>
            <%= link_to "Ir a este cliente", client, class: "btn btn-outline-secondary" %>
          </p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to "Ingresar nuevo cliente", new_client_path, class: "btn btn-outline-secondary" %>

app/views/clients/new.html.erb
<h1>Nuevo cliente</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Volver a los clientes", clients_path, class:"btn btn-outline-secondary" %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Asignar pelicula", edit_client_path(@client), class:"btn btn-outline-secondary" %> |
  <%= link_to "Volver a los clientes", clients_path, class:"btn btn-outline-secondary" %>

  <%= button_to "Eliminar este cliente", @client, method: :delete, class:"btn btn-outline-secondary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blockbuster</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#">Blockbuster</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
          <%= link_to "Peliculas", movies_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Arrendar", clients_path, class:"nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Main Content -->
  <div class="container mt-4">
        <%= yield %>
  </div>
  <!-- Footer -->
  <footer class="bg-light mt-5 py-4">
    <div class="container text-center">
      <ul class="list-inline">
        <li class="list-inline-item">
          <a href="#" target="_blank">
            <i class="fab fa-facebook-f fa-lg"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="#" target="_blank">
            <i class="fab fa-twitter fa-lg"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a href="#" target="_blank">
            <i class="fab fa-instagram fa-lg"></i>
          </a>
        </li>
      </ul>
      <p class="mb-0">&copy; 2023 Blockbuster. All rights reserved.</p>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :Caratula, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id(movie) %>" style="width: 50%; padding: 20px; background-color: #f2f2f2; border: 1px solid #ccc; margin-bottom: 20px;">
  <p style="font-size: 18px; color: #333; margin-bottom: 10px;">
    <strong>Nombre:</strong> <%= movie.name %>
  </p>

  <%= image_tag movie.image, style: "max-width: 100%; height: auto; margin-bottom: 10px;" %>

  <% if movie.clients.present? %>
    <p style="font-size: 16px; color: #333; margin-bottom: 5px;">Clientes:</p>
    <ul style="list-style: none; padding: 0;">
      <% movie.clients.each do |client| %>
        <li style="margin-bottom: 5px;">
          <strong>Nombre del cliente:</strong> <%= client.name %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No hay clientes actualmente rentando esta película</p>
  <% end %>
</div>

app/views/movies/edit.html.erb
<div style="width: 50%; margin: 0 auto;">
  <%= form_for @movie do |f| %>
    <div class="form-group">
      <%= f.label :Nombre %>
      <%= f.text_field :name, class: "form-control", readonly: true %>
    </div>

    <div class="form-group">
      <%= f.label :clientes  %>
      <%= f.collection_select :client_ids, @clients, :id, :name, {}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Guardar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Agregar una nueva pelicula", new_movie_path, class: "btn btn-outline-secondary" %><br/><br/>

<h1>Peliculas</h1>

<div id="movies" class="row">
  <% @movies.each_slice(3) do |movie_slice| %>
    <div class="row">
      <% movie_slice.each do |movie| %>
        <div class="col-md-4">
          <div class="movie-card">
            <%= render movie %>
            <p>
              <%= link_to "Ir a esta película", movie, class: "btn btn-outline-secondary" %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center">
  <nav aria-label="Page navigation">
    <ul class="pagination">
      <%== pagy_bootstrap_nav(@pagy) %>
    </ul>
  </nav>
</div>

app/views/movies/new.html.erb
<h1>Ingresar nueva pelicula</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Volver a las peliculas", movies_path, class:"btn btn-outline-secondary" %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Editar esta película", edit_movie_path(@movie), class:"btn btn-outline-secondary" %> |
  <%= link_to "Volver a películas", movies_path, class:"btn btn-outline-secondary" %>

  <%= button_to "Eliminar esta pelicula", @movie, method: :delete, class:"btn btn-outline-secondary" %>
</div>